---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: attendee-service-source

outputs:
- name: current-app-info

run:
  path: attendee-service-source/ci/tasks/current-app-get-info.sh
